### ISSUE TITLE
Todo before complete setup

### ISSUE THREAD

**Issue by CasperWA** [emmo-repo/domain-photovoltaics#1]
These items should be done before the repository is considered to be completely setup:

- [ ] Setup Deploy Onto! (onto-ns.com)
- [x] Setup a "collective" ontology file (`domain_photovoltaics.ttl` or similar)
- [x] Add meaningful catalog file for proper referencing (and importing) EMMO
- [ ] Add documentation setup, including continuous integration and deployment (CI/CD)

**Comment by CasperWA** [comment]
The collective ontology should follow the hierarchy: pv < electrochemistry < generic-concepts < emmo.

**Comment by CasperWA** [comment]
The collective ontology will be called `domain_photovoltaics.ttl`, whereas the (first) working ontology file will be called `photovoltaics.ttl`.
I.e., all part-ontologies will be gathered in `domain_photovoltaics.ttl`, which represents the ontology as a whole.

**Comment by CasperWA** [comment]
The last things are still missing, so I will open this again until they've been implemented.
